ALTER TABLE BitShift_FirstData_StoreSetting ADD AllowVisa bit NOT NULL DEFAULT(1)
ALTER TABLE BitShift_FirstData_StoreSetting ADD AllowMastercard bit NOT NULL DEFAULT(1)
ALTER TABLE BitShift_FirstData_StoreSetting ADD AllowAmex bit NOT NULL DEFAULT(1)
ALTER TABLE BitShift_FirstData_StoreSetting ADD AllowDiscover bit NOT NULL DEFAULT(1)

INSERT INTO LocaleStringResource (LanguageId, ResourceName, ResourceValue) VALUES (1, 'BitShift.Plugin.FirstData.Fields.AllowVisa', 'Allow Visa')
INSERT INTO LocaleStringResource (LanguageId, ResourceName, ResourceValue) VALUES (1, 'BitShift.Plugin.FirstData.Fields.AllowVisa.Hint', 'Uncheck if you want to block Visa payments')
INSERT INTO LocaleStringResource (LanguageId, ResourceName, ResourceValue) VALUES (1, 'BitShift.Plugin.FirstData.Fields.AllowMastercard', 'Allow Mastercard')
INSERT INTO LocaleStringResource (LanguageId, ResourceName, ResourceValue) VALUES (1, 'BitShift.Plugin.FirstData.Fields.AllowMastercard.Hint', 'Uncheck if you want to block Mastercard payments')
INSERT INTO LocaleStringResource (LanguageId, ResourceName, ResourceValue) VALUES (1, 'BitShift.Plugin.FirstData.Fields.AllowAmex', 'Allow American Express')
INSERT INTO LocaleStringResource (LanguageId, ResourceName, ResourceValue) VALUES (1, 'BitShift.Plugin.FirstData.Fields.AllowAmex.Hint', 'Uncheck if you want to block American Express payments')
INSERT INTO LocaleStringResource (LanguageId, ResourceName, ResourceValue) VALUES (1, 'BitShift.Plugin.FirstData.Fields.AllowDiscover', 'Allow Discover')
INSERT INTO LocaleStringResource (LanguageId, ResourceName, ResourceValue) VALUES (1, 'BitShift.Plugin.FirstData.Fields.AllowDiscover.Hint', 'Uncheck if you want to block Discover payments')
INSERT INTO LocaleStringResource (LanguageId, ResourceName, ResourceValue) VALUES (1, 'Payment.CardNumber.NotAccepted', 'That card type is not accepted')